# Generated by Django 5.0 on 2024-11-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'username')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('insta_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('like', 'like'), ('comment', 'comment'), ('posts', 'posts'), ('followers', 'followers'), ('following', 'following'), ('engagement_rate', 'engagement_rate')], max_length=255, null=True)),
                ('count', models.PositiveIntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('insta_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(blank=True, choices=[('post-like', 'post-like'), ('post-comment', 'post-comment'), ('comment-like', 'comment-like'), ('reels-view', 'reels-view'), ('reels-like', 'reels-like'), ('reels-comment', 'reels-comment'), ('hashtag-like', 'hashtag-like'), ('hashtag-comment', 'hashtag-comment')], max_length=50, null=True)),
                ('user_comment', models.TextField(blank=True, default='', null=True)),
                ('url', models.TextField(default='')),
                ('view_story', models.BooleanField(default=False)),
                ('like_story', models.BooleanField(default=False)),
                ('like_option', models.CharField(blank=True, choices=[('first', 'First'), ('last', 'Last'), ('last & first', 'Last & first'), ('last 2', 'Last 2'), ('last 3', 'Last 3'), ('last 4', 'Last 4'), ('last 5', 'Last 5')], max_length=20, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Completed')], default=0)),
                ('insta_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('day', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_time', to='userapi.target')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('image', models.ImageField(default='User/dummy.jpg', upload_to='User/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
