# Generated by Django 5.0 on 2024-11-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='like_option',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('last', 'Last'), ('last & first', 'Last & first'), ('all', 'All')], max_length=20, null=True),
        ),
    ]
