# Generated by Django 5.0 on 2024-11-15 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_target_like_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
        migrations.AlterField(
            model_name='stat',
            name='insta_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='userapi.credential'),
        ),
    ]
