# Generated by Django 5.0 on 2023-12-13 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0002_alter_hashtag_target_alter_post_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.targettype'),
        ),
        migrations.AlterField(
            model_name='target',
            name='actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.action'),
        ),
        migrations.AlterField(
            model_name='target',
            name='activity_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.activitytime'),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.targettype'),
        ),
    ]
