# Generated by Django 5.0 on 2023-12-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0003_alter_action_action_target_type_alter_target_actions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targettype',
            name='type',
            field=models.CharField(choices=[('hashtags', 'hashtags'), ('posts', 'posts'), ('reels', 'reels')], max_length=255),
        ),
    ]
