# Generated by Django 5.0 on 2023-12-15 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0005_action_time_stamp_credential_profile_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstaCredential',
            new_name='Credential',
        ),
    ]
