# Generated by Django 5.0 on 2023-12-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0009_alter_activitytime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Completed')], default=0),
        ),
    ]
