# Generated by Django 5.0 on 2023-12-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0010_target_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reel',
            name='url',
            field=models.TextField(),
        ),
    ]
