# Generated by Django 5.0 on 2023-12-26 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0011_alter_post_url_alter_reel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='insta_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential'),
        ),
    ]
