# Generated by Django 5.0 on 2023-12-26 20:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0012_target_insta_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('user', 'username')},
        ),
    ]
