# Generated by Django 5.0 on 2024-01-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0014_hashtag_type_post_type_reel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
