# Generated by Django 5.0 on 2024-01-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0015_stat_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targettype',
            name='type',
            field=models.CharField(choices=[('post-like', 'post-like'), ('post-comment', 'post-comment'), ('comment-like', 'comment-like'), ('reels-view', 'reels-view'), ('reels-like', 'reels-like'), ('reels-comment', 'reels-comment'), ('hashtag-like', 'hashtag-like'), ('hashtag-comment', 'hashtag-comment')], max_length=255),
        ),
    ]
