# Generated by Django 5.0 on 2024-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0016_alter_targettype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
