# Generated by Django 5.0 on 2024-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0017_remove_comment_comment_remove_hashtag_hashtag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
