# Generated by Django 5.0 on 2024-01-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0019_rename_followers_stat_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='insta_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential'),
        ),
    ]
