# Generated by Django 5.0 on 2024-09-19 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapi', '0024_alter_target_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='insta_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapi.credential'),
        ),
    ]
